STRINGS: dict[str, str] = {
    "window_title": "N1700 Bridge",
    "part_id_label": "Part ID",
    "export_btn": "Export Excel",
    "save_btn": "Save",
    "saved_toast": "Register configuration saved",
    "status_plc_connected": "PLC: Connected",
    "status_plc_disconnected": "PLC: Disconnected",
    "status_n1700_available": "N1700: Ready",
    "status_n1700_unavailable": "N1700: Not found",
    "status_excel_open": "Excel: Open",
    "status_excel_closed": "Excel: Closed",
    "error_n1700_not_found": "N1700 window not found",
    "error_excel_closed": "Excel file was closed. Please reopen it.",
    "verdict_ok": "OK",
    "verdict_ng": "NG",
    "register_address_label": "Reg Addr",
    "judgment_label": "Verdict",
    "judgment_address_label": "Verdict Addr",
    "time_column": "Time",
    "barcode_placeholder": "Scan barcode...",
    "barcode_reset_btn": "Re-scan",
    "export_success": "Report exported: {}",
    "export_error": "Export error: {}",
    "export_empty": "No data to export",
    "multiplier_label": "Multiplier",
    "error_dll_disconnected": "N1700 DLL not connected. Check USB.",
    "error_dll_timeout": "N1700 DLL timeout. Check USB connection.",
    "error_dll_poll": "Error reading data from N1700 DLL.",
    "error_dll_general": "N1700 DLL error.",
    "output_cell_label": "Output Cell",
    "lower_label": "Min",
    "upper_label": "Max",
    "computed_label": "Result",
    "template_label": "Template",
    "template_browse_btn": "Browse...",
    "template_sheet_label": "Sheet",
    "template_input_label": "Input cells",
    "group_name_label": "Group",
    "template_not_found": "Template file not found",
    "raw_label": "Raw",
    "zero_label": "Zero",
    "master_label": "Master",
    "part_id_column": "Part ID",
    "computed_default": "Read from Excel",
    "verdict_address_label": "Verdict Addr",
    "get_zero_btn": "Get Zero",
    "get_zero_toast": "Zero values captured from N1700",
    "get_zero_error": "Get Zero error: {}",
}
